######################################################################
# Automatically generated by qmake (3.1) Sun Aug 2 12:03:30 2026
######################################################################

TEMPLATE = app
TARGET = Document.Editor
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += plugins/example/ExamplePlugin.h \
           src/app/Application.h \
           src/app/Settings.h \
           src/converters/DocxConverter.h \
           src/converters/FtpClient.h \
           src/converters/RtfConverter.h \
           src/converters/XamlConverter.h \
           src/dialogs/AboutDialog.h \
           src/dialogs/FindDialog.h \
           src/dialogs/GoToLineDialog.h \
           src/dialogs/InsertChartDialog.h \
           src/dialogs/InsertDateDialog.h \
           src/dialogs/InsertImageDialog.h \
           src/dialogs/InsertLineDialog.h \
           src/dialogs/InsertLinkDialog.h \
           src/dialogs/InsertShapeDialog.h \
           src/dialogs/InsertSymbolDialog.h \
           src/dialogs/InsertTableDialog.h \
           src/dialogs/InsertTimeDialog.h \
           src/dialogs/InsertVideoDialog.h \
           src/dialogs/LineSpacingDialog.h \
           src/dialogs/OptionsDialog.h \
           src/dialogs/ReplaceDialog.h \
           src/dialogs/SpellCheckDialog.h \
           src/editor/DocumentEditor.h \
           src/editor/DocumentManager.h \
           src/editor/DocumentTab.h \
           src/mainwindow/ActionManager.h \
           src/mainwindow/MainWindow.h \
           src/mainwindow/StatusBarManager.h \
           src/mainwindow/ThemeManager.h \
           src/plugins/IPlugin.h \
           src/plugins/PluginContext.h \
           src/plugins/PluginManager.h \
           src/services/DocumentService.h \
           src/services/SpellCheckHighlighter.h \
           src/utils/DpiUtils.h \
           src/utils/NetworkUtils.h \
           src/utils/SpellChecker.h \
           src/utils/TextUtils.h \
           src/widgets/RulerWidget.h \
           src/widgets/SymbolPicker.h \
           src/widgets/TableGridPicker.h \
           third_party/miniz/miniz.h \
           third_party/miniz/miniz_common.h \
           third_party/miniz/miniz_export.h \
           third_party/miniz/miniz_tdef.h \
           third_party/miniz/miniz_tinfl.h \
           third_party/miniz/miniz_zip.h
SOURCES += src/main.cpp \
           test/test_DocumentEditor.cpp \
           test/test_DocumentManager.cpp \
           test/test_DocumentService.cpp \
           test/test_DocxConverter.cpp \
           test/test_DpiUtils.cpp \
           test/test_FtpClient.cpp \
           test/test_NetworkUtils.cpp \
           test/test_PluginManager.cpp \
           test/test_RtfConverter.cpp \
           test/test_Settings.cpp \
           test/test_SpellChecker.cpp \
           test/test_TextUtils.cpp \
           test/test_ThemeManager.cpp \
           test/test_XamlConverter.cpp \
           plugins/example/ExamplePlugin.cpp \
           src/app/Application.cpp \
           src/app/Settings.cpp \
           src/converters/DocxConverter.cpp \
           src/converters/FtpClient.cpp \
           src/converters/RtfConverter.cpp \
           src/converters/XamlConverter.cpp \
           src/dialogs/AboutDialog.cpp \
           src/dialogs/FindDialog.cpp \
           src/dialogs/GoToLineDialog.cpp \
           src/dialogs/InsertChartDialog.cpp \
           src/dialogs/InsertDateDialog.cpp \
           src/dialogs/InsertImageDialog.cpp \
           src/dialogs/InsertLineDialog.cpp \
           src/dialogs/InsertLinkDialog.cpp \
           src/dialogs/InsertShapeDialog.cpp \
           src/dialogs/InsertSymbolDialog.cpp \
           src/dialogs/InsertTableDialog.cpp \
           src/dialogs/InsertTimeDialog.cpp \
           src/dialogs/InsertVideoDialog.cpp \
           src/dialogs/LineSpacingDialog.cpp \
           src/dialogs/OptionsDialog.cpp \
           src/dialogs/ReplaceDialog.cpp \
           src/dialogs/SpellCheckDialog.cpp \
           src/editor/DocumentEditor.cpp \
           src/editor/DocumentManager.cpp \
           src/editor/DocumentTab.cpp \
           src/mainwindow/ActionManager.cpp \
           src/mainwindow/MainWindow.cpp \
           src/mainwindow/StatusBarManager.cpp \
           src/mainwindow/ThemeManager.cpp \
           src/plugins/PluginContext.cpp \
           src/plugins/PluginManager.cpp \
           src/services/DocumentService.cpp \
           src/services/SpellCheckHighlighter.cpp \
           src/utils/DpiUtils.cpp \
           src/utils/NetworkUtils.cpp \
           src/utils/SpellChecker.cpp \
           src/utils/TextUtils.cpp \
           src/widgets/RulerWidget.cpp \
           src/widgets/SymbolPicker.cpp \
           src/widgets/TableGridPicker.cpp \
           third_party/miniz/miniz.c \
           third_party/miniz/miniz_tdef.c \
           third_party/miniz/miniz_tinfl.c \
           third_party/miniz/miniz_zip.c \
           build/src/de_objects_autogen/mocs_compilation.cpp \
           build/src/Document.Editor_autogen/mocs_compilation.cpp \
           build/test/test_DocumentEditor_autogen/mocs_compilation.cpp \
           build/test/test_DocumentManager_autogen/mocs_compilation.cpp \
           build/test/test_DocumentService_autogen/mocs_compilation.cpp \
           build/test/test_DocxConverter_autogen/mocs_compilation.cpp \
           build/test/test_DpiUtils_autogen/mocs_compilation.cpp \
           build/test/test_FtpClient_autogen/mocs_compilation.cpp \
           build/test/test_NetworkUtils_autogen/mocs_compilation.cpp \
           build/test/test_PluginManager_autogen/mocs_compilation.cpp \
           build/test/test_RtfConverter_autogen/mocs_compilation.cpp \
           build/test/test_Settings_autogen/mocs_compilation.cpp \
           build/test/test_SpellChecker_autogen/mocs_compilation.cpp \
           build/test/test_TextUtils_autogen/mocs_compilation.cpp \
           build/test/test_ThemeManager_autogen/mocs_compilation.cpp \
           build/test/test_XamlConverter_autogen/mocs_compilation.cpp \
           build/CMakeFiles/4.4.0/CompilerIdC/CMakeCCompilerId.c \
           build/CMakeFiles/4.4.0/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/plugins/example/ExamplePlugin_autogen/mocs_compilation.cpp \
           build/src/Document.Editor_autogen/7BV4YJK25R/qrc_resources.cpp \
           build/third_party/miniz/miniz_autogen/mocs_compilation.cpp
RESOURCES += resources/resources.qrc
TRANSLATIONS += build/src/CMakeFiles/de_objects.dir/compiler_depend.ts \
                build/src/CMakeFiles/de_objects_autogen.dir/compiler_depend.ts \
                build/src/CMakeFiles/de_objects_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/src/CMakeFiles/Document.Editor.dir/compiler_depend.ts \
                build/src/CMakeFiles/Document.Editor_autogen.dir/compiler_depend.ts \
                build/src/CMakeFiles/Document.Editor_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentEditor.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentEditor_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentEditor_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentManager.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentManager_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentManager_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentService.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentService_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocumentService_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocxConverter.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocxConverter_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DocxConverter_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DpiUtils.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DpiUtils_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_DpiUtils_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_FtpClient.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_FtpClient_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_FtpClient_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_NetworkUtils.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_NetworkUtils_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_NetworkUtils_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_PluginManager.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_PluginManager_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_PluginManager_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_RtfConverter.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_RtfConverter_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_RtfConverter_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_Settings.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_Settings_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_Settings_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_SpellChecker.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_SpellChecker_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_SpellChecker_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_TextUtils.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_TextUtils_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_TextUtils_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_ThemeManager.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_ThemeManager_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_ThemeManager_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_XamlConverter.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_XamlConverter_autogen.dir/compiler_depend.ts \
                build/test/CMakeFiles/test_XamlConverter_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/plugins/example/CMakeFiles/ExamplePlugin.dir/compiler_depend.ts \
                build/plugins/example/CMakeFiles/ExamplePlugin_autogen.dir/compiler_depend.ts \
                build/plugins/example/CMakeFiles/ExamplePlugin_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/third_party/miniz/CMakeFiles/miniz.dir/compiler_depend.ts \
                build/third_party/miniz/CMakeFiles/miniz_autogen.dir/compiler_depend.ts \
                build/third_party/miniz/CMakeFiles/miniz_autogen_timestamp_deps.dir/compiler_depend.ts
